#!/usr/bin/env Rscript
# Paper adaptation: MA120 + EMA12/EMA30 + RSI7, ATR stops and risk sizing.
# Usage: Rscript build.R india|us

suppressMessages({library(RODBC); library(RPostgres); library(data.table); library(TTR)})
options(stringsAsFactors=FALSE, scipen=100)
source("/mnt/hollandC/StockViz/R/config.r")
arg<-commandArgs(trailingOnly=TRUE); if(length(arg)!=1||!arg%in%c("india","us"))stop("usage: Rscript build.R india|us")
MARKET<-arg[[1]]; ROOT<-file.path("/mnt/ssd1/stockviz/R2/backtests/Trend Filtering and Momentum Signals",MARKET); dir.create(ROOT,recursive=TRUE,showWarnings=FALSE)
LOOKBACK<-365L; WARMUP<-140L; N_POSITIONS<-20L; DRAG<-if(MARKET=="india")0.005 else 0.0025; FF_TIERS<-c(.60,.70)
EMA_SHORT<-12L; EMA_MID<-30L; MA_TREND<-120L; RSI_LEN<-7L; RSI_THRESHOLD<-45; ATR_LEN<-14L; STOP_MULT<-1.2; TRAIL_MULT<-1.0; VOL_LEN<-60L; TARGET_VOL<-.12; RISK_PCT<-.015
quote_sql<-function(x)paste(sprintf("'%s'",gsub("'","''",x)),collapse=",")
pct_rank<-function(x){z<-rep(NA_real_,length(x));ok<-is.finite(x);if(sum(ok)>1)z[ok]<-(rank(x[ok],ties.method="average")-1)/(sum(ok)-1);z}
metric_one<-function(x,start=NA,end=NA){if(!is.na(start))x<-x[DATE>=as.Date(start)];if(!is.na(end))x<-x[DATE<=as.Date(end)];x<-x[is.finite(RETURN)];if(nrow(x)<20||sd(x$RETURN)==0)return(data.table(N=nrow(x),CAGR=NA,Vol=NA,Sharpe=NA,MaxDD=NA,Turnover=sum(x$TURNOVER),AvgExposure=mean(x$EXPOSURE)));w<-cumprod(1+x$RETURN);yrs<-as.numeric(max(x$DATE)-min(x$DATE))/365.25;dd<-w/cummax(w)-1;data.table(N=nrow(x),CAGR=tail(w,1)^(1/yrs)-1,Vol=sd(x$RETURN)*sqrt(252),Sharpe=mean(x$RETURN)/sd(x$RETURN)*sqrt(252),MaxDD=min(dd),Turnover=sum(x$TURNOVER),AvgExposure=mean(x$EXPOSURE))}
con<-odbcDriverConnect(sprintf("Driver={ODBC Driver 17 for SQL Server};Server=%s;Database=%s;Uid=%s;Pwd=%s;",ldbserver,if(MARKET=="india")"StockViz" else "StockVizUs2",ldbuser,ldbpassword),case="nochange",believeNRows=TRUE); pg<-NULL
on.exit({try(odbcClose(con),silent=TRUE);if(!is.null(pg))try(dbDisconnect(pg),silent=TRUE)},add=TRUE)
if(MARKET=="india"){
  pg<-dbConnect(RPostgres::Postgres(),host="sweden",user=ldbuser2,password=ldbpassword2,dbname="StockVizDyn",sslmode="allow")
  ffq<-sqlQuery(con,"select SYMBOL,TIME_STAMP,FF_MKT_CAP_CR from EQUITY_MISC_INFO where FF_MKT_CAP_CR is not null")
  if(!is.data.frame(ffq))stop("FF query failed"); ff<-as.data.table(ffq);setnames(ff,toupper(names(ff)));ff[,`:=`(SYMBOL=trimws(as.character(SYMBOL)),DATE=as.Date(TIME_STAMP),FF_MKT_CAP_CR=as.numeric(FF_MKT_CAP_CR))];ff<-ff[is.finite(FF_MKT_CAP_CR)&!is.na(DATE)];setkey(ff,SYMBOL,DATE)
  pxq<-dbGetQuery(pg,"select ticker as SYMBOL,date_stamp as DATE,o as OPEN,h as HIGH,l as LOW,c as CLOSE from eod_adjusted_nse where date_stamp >= '2005-01-01' and o>0 and h>0 and l>0 and c>0 order by ticker,date_stamp");if(!is.data.frame(pxq))stop("India price query failed")
}else{
  cq<-sqlQuery(con,"select PERIOD,SYMBOL from SP500_CONSTITUENTS where INDEX_NAME='SPX'");if(!is.data.frame(cq))stop("constituent query failed");const<-as.data.table(cq);setnames(const,toupper(names(const)));const[,`:=`(PERIOD=as.Date(PERIOD),SYMBOL=trimws(as.character(SYMBOL)))];const<-unique(const[!is.na(PERIOD)&SYMBOL!=""]);periods<-sort(unique(const$PERIOD));syms<-sort(unique(const$SYMBOL))
  pxq<-as.data.table(sqlQuery(con,sprintf("select SYMBOL,TIME_STAMP as DATE,C as PX_CLOSE from BHAV_EQ_TD where TIME_STAMP >= '2005-01-01' and C>0 and SYMBOL in (%s) order by SYMBOL,TIME_STAMP",quote_sql(syms))));if(!is.data.frame(pxq))stop("US price query failed");pxq[,CLOSE:=PX_CLOSE];pxq[,`:=`(OPEN=CLOSE,HIGH=CLOSE,LOW=CLOSE)]
}
px<-as.data.table(pxq);setnames(px,toupper(names(px)));px[,`:=`(SYMBOL=trimws(as.character(SYMBOL)),DATE=as.Date(DATE),OPEN=as.numeric(OPEN),HIGH=as.numeric(HIGH),LOW=as.numeric(LOW),CLOSE=as.numeric(CLOSE))];px<-unique(px[is.finite(OPEN)&is.finite(HIGH)&is.finite(LOW)&is.finite(CLOSE)&OPEN>0&HIGH>0&LOW>0&CLOSE>0],by=c("SYMBOL","DATE"));setorder(px,SYMBOL,DATE);setindex(px,DATE);px_by<-split(px,by="SYMBOL",keep.by=TRUE);data_dates<-sort(unique(px$DATE));month_dates<-data.table(DATE=data_dates,MONTH=format(data_dates,"%Y-%m"))[,.(DATE=max(DATE)),by=MONTH]$DATE
if(MARKET=="us")const_at<-function(d){i<-findInterval(d,periods);if(i<1)character()else const[PERIOD==periods[i],SYMBOL]}
calc_features<-function(p){nrowp<-nrow(p);if(nrowp<WARMUP+1L)return(NULL);cl<-p$CLOSE;tr<-pmax(p$HIGH-p$LOW,abs(p$HIGH-shift(cl,1L)),abs(p$LOW-shift(cl,1L)));atr<-TTR::SMA(tr,ATR_LEN);sma<-TTR::SMA(cl,MA_TREND);e1<-TTR::EMA(cl,EMA_SHORT);e2<-TTR::EMA(cl,EMA_MID);rsi<-TTR::RSI(cl,RSI_LEN);rv<-TTR::runSD(log(cl/shift(cl,1L)),VOL_LEN)*sqrt(252);target<-as.Date(p$DATE)-LOOKBACK;mi<-findInterval(target,p$DATE);mom<-rep(NA_real_,nrowp);ok<-mi>0;mom[ok]<-cl[ok]/cl[mi[ok]]-1;data.table(p[,.(DATE,SYMBOL,OPEN,HIGH,LOW,CLOSE)],SMA120=sma,EMA12=e1,EMA30=e2,RSI7=rsi,ATR14=atr,VOL60=rv,MOM365=mom)}
feat_list<-lapply(px_by,calc_features);feat_list<-feat_list[!vapply(feat_list,is.null,logical(1))];features<-rbindlist(feat_list,fill=TRUE);setorder(features,DATE,SYMBOL);features<-features[is.finite(SMA120)&is.finite(EMA12)&is.finite(EMA30)&is.finite(RSI7)&is.finite(ATR14)&is.finite(VOL60)&is.finite(MOM365)];setorder(features,SYMBOL,DATE);features[,RSI7_PREV:=shift(RSI7),by=SYMBOL];setorder(features,DATE,SYMBOL);setkey(features,SYMBOL,DATE);setindex(features,DATE)
# Monthly signal table. Paper signal is RSI recovery-cross interpretation; basic momentum is the same point-in-time universe ranked by MOM365.
signals<-list()
for(d in month_dates){dd<-as.Date(d,origin="1970-01-01");fs<-features[DATE==dd];if(!nrow(fs))next;if(MARKET=="us")fs<-fs[SYMBOL%in%const_at(dd)] else fs<-merge(fs,ff[.(fs$SYMBOL,dd),.(SYMBOL,FF_MKT_CAP_CR),roll=TRUE],by="SYMBOL",all.x=TRUE)[is.finite(FF_MKT_CAP_CR)];if(MARKET=="us")fs[,FF_MKT_CAP_CR:=NA_real_];setorder(fs,SYMBOL,DATE);fs[,PAPER_SIGNAL:=CLOSE>SMA120 & EMA12>EMA30 & RSI7_PREV<=RSI_THRESHOLD & RSI7>RSI_THRESHOLD];fs[,r_mom:=pct_rank(MOM365)];fs[,SCORE:=r_mom];signals[[as.character(d)]]<-fs[,.(DATE,SYMBOL,CLOSE,OPEN,HIGH,LOW,ATR14,SMA120,EMA12,EMA30,RSI7,VOL60,MOM365,PAPER_SIGNAL,SCORE,FF_MKT_CAP_CR)]}
sig<-rbindlist(signals,fill=TRUE);fwrite(sig,file.path(ROOT,"signals_monthly.csv"));if(!nrow(sig))stop("no signals")
# Point-in-time monthly top-20 orders.
orders<-list();for(d in sort(unique(sig$DATE))){fs<-sig[DATE==d];if(MARKET=="india"){for(tier in FF_TIERS){cut<-quantile(fs$FF_MKT_CAP_CR,1-tier,na.rm=TRUE,names=FALSE);e<-fs[FF_MKT_CAP_CR>=cut];orders[[paste(d,"paper",tier)]]<-data.table(DATE=d,SYSTEM=sprintf("Paper_FF%d",100*tier),SYMBOL=head(e[PAPER_SIGNAL==TRUE][order(-SCORE,SYMBOL)]$SYMBOL,N_POSITIONS));orders[[paste(d,"mom",tier)]]<-data.table(DATE=d,SYSTEM=sprintf("Momentum_FF%d",100*tier),SYMBOL=head(e[order(-MOM365,SYMBOL)]$SYMBOL,N_POSITIONS))}}else{e<-fs;orders[[paste(d,"paper")]]<-data.table(DATE=d,SYSTEM="Paper_SP500",SYMBOL=head(e[PAPER_SIGNAL==TRUE][order(-SCORE,SYMBOL)]$SYMBOL,N_POSITIONS));orders[[paste(d,"mom")]]<-data.table(DATE=d,SYSTEM="Momentum_SP500",SYMBOL=head(e[order(-MOM365,SYMBOL)]$SYMBOL,N_POSITIONS))}}
orders<-rbindlist(orders,fill=TRUE);orders<-orders[SYMBOL!=""&!is.na(SYMBOL)];fwrite(orders,file.path(ROOT,"orders_monthly.csv"))
# Daily close-to-close benchmark and event-driven paper portfolio.
price_by<-px_by; systems<-grep("^Paper_",unique(orders$SYSTEM),value=TRUE);daily_out<-list();trade_out<-list()
for(sys in systems){ord<-orders[SYSTEM==sys];hold<-data.table(SYMBOL=character(),ENTRY=as.Date(character()),SHARES=integer(),STOP=numeric(),HIGH_WATER=numeric(),ATR_ENTRY=numeric());cash<-1e6;prev_nav<-cash;rows<-list();trades<-list();for(i in seq_along(data_dates)){d<-data_dates[i];dd<-as.Date(d,origin="1970-01-01");day<-px[DATE==dd];if(!nrow(day))next
    # Exit and mark existing positions. Stop uses the previous stop before today's bar.
    if(nrow(hold)){for(h in seq_len(nrow(hold))){s<-hold$SYMBOL[h];q<-day[SYMBOL==s];if(!nrow(q))next;stop<-hold$STOP[h];exit<-NA_real_;reason<-NA_character_;if(q$OPEN<stop){exit<-q$OPEN;reason<-"gap_stop"}else if(q$LOW<=stop){exit<-stop;reason<-"atr_stop"}else{f<-features[SYMBOL==s&DATE==d];if(nrow(f)&&f$CLOSE<f$SMA120){exit<-q$CLOSE;reason<-"ma_exit"}};if(is.finite(exit)){cash<-cash+hold$SHARES[h]*exit;trades[[length(trades)+1L]]<-data.table(SYSTEM=sys,SYMBOL=s,ENTRY_DATE=hold$ENTRY[h],EXIT_DATE=d,ENTRY_PRICE=NA_real_,EXIT_PRICE=exit,SHARES=hold$SHARES[h],EXIT_REASON=reason,INTENDED_RISK=hold$SHARES[h]*hold$ATR_ENTRY*STOP_MULT,REALIZED_GROSS=NA_real_);hold<-hold[-h];break}}}
    # Monthly orders enter on the first observed day after the signal date.
    sd0<-ord[DATE<d,.SD[.N],by=SYMBOL];if(nrow(sd0)&&nrow(hold)<N_POSITIONS){for(s in sd0$SYMBOL){if(s%in%hold$SYMBOL||nrow(hold)>=N_POSITIONS)next;f<-features[SYMBOL==s&DATE<d][.N];q<-day[SYMBOL==s];if(!nrow(f)||!nrow(q)||!is.finite(f$ATR14)||f$ATR14<=0)next;eq<-cash+sum(hold$SHARES*vapply(hold$SYMBOL,function(z){qq<-day[SYMBOL==z];if(nrow(qq))qq$CLOSE else 0},numeric(1)));risk<-eq*RISK_PCT;ps<-f$ATR14*STOP_MULT;vs<-if(is.finite(f$VOL60)&&f$VOL60>0)min(1,TARGET_VOL/f$VOL60)else 1;sh<-floor(risk/ps*vs);gross<-sum(hold$SHARES*vapply(hold$SYMBOL,function(z){qq<-day[SYMBOL==z];if(nrow(qq))qq$OPEN else 0},numeric(1)));remaining<-max(0,eq-gross);sh<-min(sh,floor(remaining/q$OPEN));if(sh<1)next;cash<-cash-sh*q$OPEN;hold<-rbind(hold,data.table(SYMBOL=s,ENTRY=d,SHARES=as.integer(sh),STOP=q$OPEN-ps,HIGH_WATER=q$OPEN,ATR_ENTRY=f$ATR14))}}
    # Mark at close and update trailing stops only after today's bar.
    nav<-cash;if(nrow(hold)){for(h in seq_len(nrow(hold))){q<-day[SYMBOL==hold$SYMBOL[h]];if(nrow(q)){nav<-nav+hold$SHARES[h]*q$CLOSE;hold$HIGH_WATER[h]<-max(hold$HIGH_WATER[h],q$HIGH);f<-features[SYMBOL==hold$SYMBOL[h]&DATE==d];if(nrow(f)&&is.finite(f$ATR14))hold$STOP[h]<-max(hold$STOP[h],hold$HIGH_WATER[h]-TRAIL_MULT*f$ATR14)}}};ret<-if(prev_nav>0)nav/prev_nav-1 else 0;turn<-0;rows[[length(rows)+1L]]<-data.table(DATE=d,RETURN=ret,TURNOVER=turn,EXPOSURE=(nav-cash)/max(nav,1),SYSTEM=sys);prev_nav<-nav}
  daily_out[[sys]]<-rbindlist(rows);trade_out[[sys]]<-rbindlist(trades,fill=TRUE)}
daily<-rbindlist(daily_out,fill=TRUE);trades<-rbindlist(trade_out,fill=TRUE)
# Reuse the already-built basic momentum time series as the benchmark, preserving its calendar and cost convention.
bench_dir<-file.path("/mnt/ssd1/stockviz/R2/backtests/momentum_cidce_eff",MARKET);bench<-fread(file.path(bench_dir,"daily_returns.csv"));bench[,DATE:=as.Date(as.numeric(DATE),origin="1970-01-01")];bench<-if(MARKET=="india")bench[SYSTEM%in%c("Momentum_FF60","Momentum_FF70")]else bench[SYSTEM=="Momentum_SP500"];bench[,EXPOSURE:=1];daily<-rbind(daily,bench,fill=TRUE);fwrite(daily,file.path(ROOT,"daily_returns.csv"));fwrite(trades,file.path(ROOT,"trades.csv"))
metrics<-rbindlist(lapply(unique(daily$SYSTEM),function(sys)rbindlist(lapply(c("full","pre","post"),function(w){b<-switch(w,full=c(NA,NA),pre=c(NA,"2019-12-31"),post=c("2020-05-01",NA));cbind(data.table(SYSTEM=sys,WINDOW=w),metric_one(daily[SYSTEM==sys],b[1],b[2]))}))));fwrite(metrics,file.path(ROOT,"metrics.csv"));fwrite(data.table(MARKET=MARKET,FEATURE_ROWS=nrow(features),SIGNAL_ROWS=nrow(sig),ORDER_ROWS=nrow(orders),TRADE_ROWS=nrow(trades),FIRST_DATE=min(data_dates),LAST_DATE=max(data_dates)),file.path(ROOT,"coverage_audit.csv"));saveRDS(list(params=list(market=MARKET,signal="MA120 + EMA12>EMA30 + RSI7 recovery above 45",lookback_calendar_days=LOOKBACK,atr_stop=STOP_MULT,trail=TRAIL_MULT,risk_pct=RISK_PCT,target_vol=TARGET_VOL,whole_share_positions=TRUE),signals=sig,orders=orders,daily_returns=daily,trades=trades,metrics=metrics),file.path(ROOT,"checkpoint.rds"));cat(sprintf("%s complete: %d features, %d orders, %d trades, %d daily rows\n",MARKET,nrow(features),nrow(orders),nrow(trades),nrow(daily)))
