#!/usr/bin/env Rscript
suppressMessages({library(data.table);library(xts);library(PerformanceAnalytics);library(tidyverse);library(ggthemes);library(viridis);library(ggrepel);library(patchwork);library(gt);library(webshot2)})
source("/mnt/ssd1/stockviz/R2/backtests/common/runtime.R");source_common("charts")
ROOT<-"/mnt/ssd1/stockviz/R2/backtests/Trend Filtering and Momentum Signals";parse_date<-function(x)if(is.numeric(x))as.Date(x,origin="1970-01-01")else as.Date(x);windows<-list(pre=c(as.Date("1900-01-01"),as.Date("2019-12-31")),post=c(as.Date("2020-05-01"),as.Date("2100-01-01")),full=c(as.Date("1900-01-01"),as.Date("2100-01-01")));slice<-function(x,b)x[index(x)>=b[1]&index(x)<=b[2]]
allm<-list();manifest<-list();for(mkt in c("india","us")){dir<-file.path(ROOT,mkt);d<-fread(file.path(dir,"daily_returns.csv"));d[,DATE:=parse_date(DATE)];ss<-lapply(split(d,d$SYSTEM),function(z)xts(z$RETURN,order.by=z$DATE));for(w in names(windows)){sl<-lapply(ss,slice,b=windows[[w]]);sl<-sl[vapply(sl,NROW,integer(1))>20];if(!length(sl))stop(sprintf("no %s %s returns",mkt,w));start<-max(vapply(sl,function(x)min(index(x)),as.Date("1900-01-01")));sl<-lapply(sl,function(x)x[index(x)>=start]);plotCumDrawdown(sl,title=sprintf("%s paper trend filter vs momentum | %s",toupper(mkt),toupper(w)),subtitle="MA120 + EMA12/EMA30 + RSI7 recovery; ATR stops; 1.5% risk; next-day causal execution",outPath=file.path(dir,sprintf("cum_dd_%s.png",w)),linetypeBySeries=TRUE,exactEnd=TRUE);cm<-rbindlist(lapply(names(sl),function(n){x<-sl[[n]];v<-as.numeric(x);wealth<-cumprod(1+v);dd<-wealth/cummax(wealth)-1;yrs<-as.numeric(max(index(x))-min(index(x)))/365.25;data.table(SYSTEM=n,WINDOW=w,N=length(v),CAGR=tail(wealth,1)^(1/yrs)-1,Vol=sd(v)*sqrt(252),Sharpe=mean(v)/sd(v)*sqrt(252),MaxDD=min(dd))}));fwrite(cm,file.path(dir,sprintf("chart_metrics_%s.csv",w)));tab<-fread(file.path(dir,"metrics.csv"))[WINDOW==w,.(`System`=SYSTEM,N,CAGR,Vol,Sharpe,MaxDD,Turnover,AvgExposure)];gt(tab)|>fmt_number(columns=c(N),decimals=0)|>fmt_percent(columns=c(CAGR,Vol,MaxDD,AvgExposure),decimals=1)|>fmt_number(columns=c(Sharpe,Turnover),decimals=2)|>data_color(columns=c(CAGR,Sharpe),palette=c("#f8696b","#ffeb84","#63be7b"))|>data_color(columns=MaxDD,palette=c("#f8696b","#ffeb84","#63be7b"))|>tab_header(title=md(sprintf("%s paper trend filter: %s",toupper(mkt),toupper(w))))|>tab_source_note(source_note="@StockViz")|>gtsave(filename=file.path(dir,sprintf("metrics_%s.png",w)));allm[[paste(mkt,w)]]<-cm;manifest[[length(manifest)+1]]<-data.table(MARKET=mkt,WINDOW=w,CHART=file.path(dir,sprintf("cum_dd_%s.png",w)),METRICS=file.path(dir,sprintf("metrics_%s.png",w)))}}
fwrite(rbindlist(manifest),file.path(ROOT,"chart_manifest.csv"));fmt<-function(x)ifelse(is.na(x),"NA",sprintf("%.1f%%",100*x));lines<-c("# Trend filtering and momentum signals","","## Protocol","","- Paper adaptation: MA120, EMA12 > EMA30, RSI7 recovery above 45, ATR14 initial stop at 1.2 ATR, 1.0 ATR trailing stop, MA120 exit, 1.5% risk sizing, and 12% target volatility.","- Signals are evaluated monthly at the close and executed from the next observed trading day. Positions use whole shares; no 100-share-lot constraint is imposed.","- Basic momentum benchmarks are imported from the preceding momentum_cidce_eff study and use the same 365-calendar-day formation convention.","- Pre ends 2019-12-31; post starts 2020-05-01; the 2020-01 through 2020-04 gap is excluded.","","## Results","")
for(mkt in c("india","us")){m<-fread(file.path(ROOT,mkt,"metrics.csv"));lines<-c(lines,sprintf("### %s",toupper(mkt)),"");for(w in c("pre","post","full")){z<-m[WINDOW==w];lines<-c(lines,sprintf("%s:",toupper(w)));for(i in seq_len(nrow(z)))lines<-c(lines,sprintf("- %s: CAGR %s, Sharpe %.2f, MaxDD %s, turnover %.2f, average exposure %s",z$SYSTEM[i],fmt(z$CAGR[i]),z$Sharpe[i],fmt(z$MaxDD[i]),z$Turnover[i],fmt(z$AvgExposure[i])));lines<-c(lines,"")}}
lines<-c(lines,"## Interpretation","","The paper strategy is tested here as a broad-universe adaptation, not as a literal reproduction of the paper's two-stock experiment. The RSI entry rule is operationalized as a recovery cross because the paper does not fully specify the trigger. The benchmark comparison and event ledger should be read alongside trade counts, stop exits, exposure, and coverage audits.","","The implementation retains the paper's risk-management idea while separating signal selection from position sizing. A favorable result is only credible if it survives the basic momentum benchmark, costs, pre/post windows, and the RSI/stop sensitivity checks described in plan.md.")
writeLines(lines,file.path(ROOT,"findings.md"));cat("Rendered paper-study charts, tables, and findings.md\n")
