#!/usr/bin/env Rscript
# Vectorized resimulation of the India paper portfolios.
# Reuses the audited month-end orders; only the slow daily event engine is replaced.
suppressMessages({library(RPostgres);library(data.table);library(TTR)})
source("/mnt/hollandC/StockViz/R/config.r")
OUT<-"/mnt/ssd1/stockviz/R2/backtests/Trend Filtering and Momentum Signals/india/vectorized";dir.create(OUT,recursive=TRUE,showWarnings=FALSE)
parent<-"/mnt/ssd1/stockviz/R2/backtests/Trend Filtering and Momentum Signals/india";orders<-fread(file.path(parent,"orders_monthly.csv"));orders[,DATE:=as.Date(DATE)];orders<-orders[grepl("^Paper_",SYSTEM)&!is.na(DATE)&!is.na(SYMBOL)&SYMBOL!=""];if(!nrow(orders))stop("no paper orders available")
syms<-sort(unique(orders$SYMBOL));pg<-dbConnect(Postgres(),host="sweden",user=ldbuser2,password=ldbpassword2,dbname="StockVizDyn",sslmode="allow");on.exit(dbDisconnect(pg),add=TRUE)
qsyms<-paste(sprintf("'%s'",gsub("'","''",syms)),collapse=",");q<-sprintf("select ticker as SYMBOL,date_stamp as DATE,o as OPEN,h as HIGH,l as LOW,c as CLOSE from eod_adjusted_nse where date_stamp >= '2005-01-01' and ticker in (%s) and o>0 and h>0 and l>0 and c>0 order by ticker,date_stamp",qsyms);px<-as.data.table(dbGetQuery(pg,q));setnames(px,toupper(names(px)));px[,`:=`(SYMBOL=trimws(as.character(SYMBOL)),DATE=as.Date(DATE),OPEN=as.numeric(OPEN),HIGH=as.numeric(HIGH),LOW=as.numeric(LOW),CLOSE=as.numeric(CLOSE))];px<-unique(px[is.finite(OPEN)&is.finite(HIGH)&is.finite(LOW)&is.finite(CLOSE)],by=c("SYMBOL","DATE"));setorder(px,SYMBOL,DATE)
# Build dense matrices once. The simulation below never scans the full long table inside its daily loop.
dates<-sort(unique(px$DATE));nd<-length(dates);ns<-length(syms);ri<-setNames(seq_len(nd),as.character(dates));ci<-setNames(seq_len(ns),syms);make_mat<-function(col){m<-matrix(NA_real_,nd,ns);r<-unname(ri[as.character(px$DATE)]);c<-unname(ci[px$SYMBOL]);ok<-!is.na(r)&!is.na(c);m[cbind(r[ok],c[ok])]<-px[[col]][ok];m}
O<-make_mat("OPEN");H<-make_mat("HIGH");L<-make_mat("LOW");C<-make_mat("CLOSE");ATR<-matrix(NA_real_,nd,ns);SMA<-matrix(NA_real_,nd,ns);VOL<-matrix(NA_real_,nd,ns)
for(j in seq_len(ns)){p<-px[SYMBOL==syms[j]];cl<-p$CLOSE;hi<-p$HIGH;lo<-p$LOW;prev<-c(NA,head(cl,-1));tr<-pmax(hi-lo,abs(hi-prev),abs(lo-prev));ii<-match(p$DATE,dates);ATR[ii,j]<-TTR::SMA(tr,14);SMA[ii,j]<-TTR::SMA(cl,120);VOL[ii,j]<-TTR::runSD(log(cl/prev),60)*sqrt(252)}
# Signal-date orders become next-session entry orders, preserving close-to-next-open causality.
next_idx<-function(d){k<-findInterval(d,dates);if(k<nd)k+1L else NA_integer_};entry_map<-list();for(k in seq_len(nrow(orders))){i<-next_idx(orders$DATE[k]);if(!is.na(i)){key<-as.character(dates[i]);entry_map[[key]]<-rbind(entry_map[[key]],orders[k,.(SYSTEM,SYMBOL)])}}
metric<-function(z,w){if(w=="pre")z<-z[DATE<=as.Date("2019-12-31")];if(w=="post")z<-z[DATE>=as.Date("2020-05-01")];z<-z[is.finite(RETURN)];wealth<-cumprod(1+z$RETURN);yrs<-as.numeric(max(z$DATE)-min(z$DATE))/365.25;dd<-wealth/cummax(wealth)-1;data.table(N=nrow(z),CAGR=tail(wealth,1)^(1/yrs)-1,Vol=sd(z$RETURN)*sqrt(252),Sharpe=mean(z$RETURN)/sd(z$RETURN)*sqrt(252),MaxDD=min(dd),Turnover=sum(z$TURNOVER),AvgExposure=mean(z$EXPOSURE))}
out<-list();trades<-list();for(sys in sort(unique(orders$SYSTEM))){jhold<-logical(ns);shares<-numeric(ns);stopv<-rep(NA_real_,ns);highwater<-rep(NA_real_,ns);atr_entry<-rep(NA_real_,ns);entry_date<-as.Date(rep(NA,ns));cash<-1e6;prev_nav<-cash;rows<-vector("list",nd);tt<-list();for(i in seq_len(nd)){d<-dates[i];active<-which(jhold&is.finite(C[i,]));if(length(active)){gap<-O[i,active]<stopv[active];hit<-!gap&L[i,active]<=stopv[active];ma<-!gap&!hit&C[i,active]<SMA[i,active];exit<-gap|hit|ma;if(any(exit)){ax<-active[exit];ep<-ifelse(gap[exit],O[i,ax],ifelse(hit[exit],stopv[ax],C[i,ax]));reason<-ifelse(gap[exit],"gap_stop",ifelse(hit[exit],"atr_stop","ma_exit"));cash<-cash+sum(shares[ax]*ep);for(k in seq_along(ax))tt[[length(tt)+1L]]<-data.table(SYSTEM=sys,SYMBOL=syms[ax[k]],ENTRY_DATE=entry_date[ax[k]],EXIT_DATE=d,ENTRY_PRICE=NA_real_,EXIT_PRICE=ep[k],SHARES=shares[ax[k]],EXIT_REASON=reason[k],INTENDED_RISK=shares[ax[k]]*atr_entry[ax[k]]*1.2);jhold[ax]<-FALSE;shares[ax]<-0;stopv[ax]<-NA;highwater[ax]<-NA;atr_entry[ax]<-NA;entry_date[ax]<-NA}}
  cand<-entry_map[[as.character(d)]];if(!is.null(cand)){cand<-cand[SYSTEM==sys];for(k in seq_len(nrow(cand))){if(sum(jhold)>=20)break;s<-match(cand$SYMBOL[k],syms);if(is.na(s)||jhold[s]||!is.finite(O[i,s]))next;eq<-cash+sum(shares[jhold]*C[i,jhold],na.rm=TRUE);a<-if(i>1)ATR[i-1,s]else NA_real_;v<-if(i>1)VOL[i-1,s]else NA_real_;if(!is.finite(a)||a<=0)next;scale<-if(is.finite(v)&&v>0)min(1,.12/v)else 1;perrisk<-1.2*a;raw<-floor(eq*.015/perrisk*scale);gross<-sum(shares[jhold]*O[i,jhold],na.rm=TRUE);capacity<-max(0,eq-gross);n<-min(raw,floor(capacity/O[i,s]));if(n<1)next;cash<-cash-n*O[i,s];jhold[s]<-TRUE;shares[s]<-n;atr_entry[s]<-a;entry_date[s]<-d;highwater[s]<-O[i,s];stopv[s]<-O[i,s]-1.2*a}}
  active<-which(jhold&is.finite(C[i,]));nav<-cash+if(length(active))sum(shares[active]*C[i,active],na.rm=TRUE)else 0;gross_mark<-if(length(active))sum(shares[active]*C[i,active],na.rm=TRUE)else 0;if(nav>0&&gross_mark>nav&&length(active)){scaled<-floor(shares[active]*nav/gross_mark);cash<-cash+sum((shares[active]-scaled)*C[i,active],na.rm=TRUE);shares[active]<-scaled;zero<-active[shares[active]<1];if(length(zero))jhold[zero]<-FALSE;active<-which(jhold&is.finite(C[i,]));nav<-cash+if(length(active))sum(shares[active]*C[i,active],na.rm=TRUE)else 0};exposure<-if(nav>0)if(length(active))sum(shares[active]*C[i,active],na.rm=TRUE)/nav else 0 else 0;rows[[i]]<-data.table(DATE=d,RETURN=if(prev_nav>0)nav/prev_nav-1 else 0,TURNOVER=0,EXPOSURE=exposure,SYSTEM=sys);if(length(active)){highwater[active]<-pmax(highwater[active],H[i,active]);upd<-is.finite(ATR[i,active]);stopv[active[upd]]<-pmax(stopv[active[upd]],highwater[active[upd]]-ATR[i,active[upd]])};prev_nav<-nav}
out[[sys]]<-rbindlist(rows);trades[[sys]]<-rbindlist(tt,fill=TRUE)}
daily<-rbindlist(out);trades_dt<-rbindlist(trades,fill=TRUE);metrics<-rbindlist(lapply(sort(unique(daily$SYSTEM)),function(s)rbindlist(lapply(c("full","pre","post"),function(w)cbind(data.table(SYSTEM=s,WINDOW=w),metric(daily[SYSTEM==s],w))))));fwrite(daily,file.path(OUT,"daily_returns.csv"));fwrite(trades_dt,file.path(OUT,"trades.csv"));fwrite(metrics,file.path(OUT,"metrics.csv"));fwrite(data.table(MARKET="india",SYSTEMS=paste(sort(unique(daily$SYSTEM)),collapse=";"),SYMBOLS=ns,PRICE_ROWS=nrow(px),DAILY_ROWS=nrow(daily),TRADE_ROWS=nrow(trades_dt),MAX_PAPER_EXPOSURE=max(daily$EXPOSURE,na.rm=TRUE),MIN_PAPER_EXPOSURE=min(daily$EXPOSURE,na.rm=TRUE)),file.path(OUT,"coverage_audit.csv"));saveRDS(list(params=list(engine="dense matrix/vectorized daily state",whole_share_positions=TRUE,gross_exposure_cap=1,risk_pct=.015,atr_stop=1.2,target_vol=.12,orders_source=file.path(parent,"orders_monthly.csv")),metrics=metrics,daily_returns=daily,trades=trades_dt),file.path(OUT,"checkpoint.rds"));cat(sprintf("vectorized India complete: %d symbols, %d prices, %d daily rows, %d trades, max exposure %.6f\n",ns,nrow(px),nrow(daily),nrow(trades_dt),max(daily$EXPOSURE,na.rm=TRUE)))
